### PR TITLE
Hlds secrets test

### PR DESCRIPTION
**Pull request by padmapriyanalam**
https://tools.hmcts.net/jira/browse/CCD-4154
Notes:
*
*
*

### CODE REVIEW

**Comment by timja** [comment]
I've converted to draft and removed review requests as this doesn't look ready for review yet.

**Comment by timja** [comment]
Closing as no progress in awhile

**Comment by madjava** [comment]
Hi @padmapriyanalam, is this PR still needed?

**Comment by padmapriyanalam** [comment]
> Hi @padmapriyanalam, is this PR still needed?

Hi @madjava , PR not needed

**Pull request closed without merging**
