### PR TITLE
DTSAM-240 Adjust jenkins PG migration end date for AM repos

### PR DESCRIPTION
**Pull request by mattnayler**
### Jira link (if applicable)

[DTSAM-240](https://tools.hmcts.net/jira/browse/DTSAM-240) _"Adjust jenkins PG migration end date for AM repos_"

### Change description ###

Adjust expiry date used in `vars/warnAboutDeprecatedPostgres.groovy` for AM repos to reflect new migration date.

### CODE REVIEW

**Review by thomast1906 — CHANGES_REQUESTED** [review]
Just checking - when is the migration date for these repos?

**Comment by mattnayler** [comment]
**AM** are in the release calendar as 22-April.  Same day as **RD**.  (So I would have been more comfortable with a date after that: rather than same date)

**Review by thomast1906 — APPROVED** [review]

**Comment by mattnayler** [comment]
Will do:  I will check in with RD team if they need the same.

**Review by kiran-yenigala-hmcts — APPROVED** [review]

**Comment by mattnayler** [comment]
I have adjusted dates as advised (thanks @thomast1906): and included RD repos as requested (@kiran-yenigala-hmcts).

**Review by kiran-yenigala-hmcts — APPROVED** [review]

**Review by thomast1906 — APPROVED** [review]

**Comment by thomast1906** [comment]
remove the additional RD repos @mattnayler - they haven't been requested (yet)

**Pull request merged**
